name: stigma
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  firebase_core: ^3.15.1
  iconsax: ^0.0.8
  lottie: ^3.3.1
  shimmer: ^3.0.0
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  flutter_native_splash: ^2.4.6
  google_sign_in: ^6.1.5
  google_maps_flutter: ^2.12.3
  carousel_slider: ^5.1.1
  lucide_icons: ^0.257.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  logger: ^2.6.0
  dotted_line: ^3.2.3
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logos.png"
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/brands/
    - assets/animation/success.json
    - assets/animation/loading.json

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
