// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uSGY16-Kke3KjyqzAqrYcYy9AjspeqQ',
    appId: '1:154376277238:web:54326417a618c71daa30d7',
    messagingSenderId: '154376277238',
    projectId: 'apnaparcel-39bfc',
    authDomain: 'apnaparcel-39bfc.firebaseapp.com',
    storageBucket: 'apnaparcel-39bfc.firebasestorage.app',
    measurementId: 'G-CTKHM0KK3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAvZiXZAxj4FY5mC3wFQMb9InUvBVPg0',
    appId: '1:154376277238:android:69ed48847590191faa30d7',
    messagingSenderId: '154376277238',
    projectId: 'apnaparcel-39bfc',
    storageBucket: 'apnaparcel-39bfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6bfbL4Q_k81k21Jg2l0kVI5SEq71TMg',
    appId: '1:154376277238:ios:4971924a833617e9aa30d7',
    messagingSenderId: '154376277238',
    projectId: 'apnaparcel-39bfc',
    storageBucket: 'apnaparcel-39bfc.firebasestorage.app',
    androidClientId: '154376277238-tim0sphvl7srnqnm3ikt6t1mbid6iq8v.apps.googleusercontent.com',
    iosClientId: '154376277238-t6r4i1mm6frojoq9rhk5rn3uh9si5tik.apps.googleusercontent.com',
    iosBundleId: 'com.example.apnaparcelfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6bfbL4Q_k81k21Jg2l0kVI5SEq71TMg',
    appId: '1:154376277238:ios:4971924a833617e9aa30d7',
    messagingSenderId: '154376277238',
    projectId: 'apnaparcel-39bfc',
    storageBucket: 'apnaparcel-39bfc.firebasestorage.app',
    androidClientId: '154376277238-tim0sphvl7srnqnm3ikt6t1mbid6iq8v.apps.googleusercontent.com',
    iosClientId: '154376277238-t6r4i1mm6frojoq9rhk5rn3uh9si5tik.apps.googleusercontent.com',
    iosBundleId: 'com.example.apnaparcelfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0uSGY16-Kke3KjyqzAqrYcYy9AjspeqQ',
    appId: '1:154376277238:web:1f2ad90726e933b7aa30d7',
    messagingSenderId: '154376277238',
    projectId: 'apnaparcel-39bfc',
    authDomain: 'apnaparcel-39bfc.firebaseapp.com',
    storageBucket: 'apnaparcel-39bfc.firebasestorage.app',
    measurementId: 'G-Z5MNWDF106',
  );

}